hyperion/blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 16 11:28:56 2023

@author: sam
"""

from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post
urlpatterns = [
    path('',
        ListView.as_view(
            queryset=
            Post.objects.all().order_by("-date")[:25],
            template_name="blog.html"
            )
        ),
    path('<int:pk>/',
        DetailView.as_view(
            model = Post,
            template_name="post.html"
) ),
]

hyperion/hyperion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/',include("webapp.urls")),
    path('blog/',include("blog.urls")),
    path('polls/',include("polls.urls")),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('', include("user_auth.urls"))
    
]

hyperion/user_auth/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 11:27:02 2023

@author: sam
"""
from django.urls import path, include, re_path
from . import views
from django.apps import apps

app_name = 'user_auth'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('show_user/', views.show_user, name='show_user'),
    path('register/',views.registration_page, name='register'),
    path('',views.registration_page, name='register')
]

hyperion/user_auth/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 19 10:52:10 2023

@author: sam
"""

from django.forms import ModelForm
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import  User

# Create your forms here.

        
        
        
class CreateUserForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
 
        fields = ['first_name','last_name','username','email','password1','password2']
        

hyperion/user_auth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib import messages
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login, logout 
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm

# Create your views here.
def user_login(request):
    """This function takes the user to the login page
    
        """
    return render(request, 'authentication/login.html')


def user_logout(request):
    """This function logs the user out and returns them to the login page
    
        """
    logout(request)
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    """This function defines how to authenticate a user. It takes the user 
        input and tries to log them in. 
        
        :param str username: This requests the user to type the username
        :param str password: This requests the user to type their corresponding
            password
        :param user: This authenticates the information entered by the user. If it 
            matches a user that has been saved in the database, then a welcome page is
            displayed by calling the show user function. If it does not match to an existing
            user, then the output will be None, and the user is redirected to the login page where
            they can select to register. 
            
            """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
            )   
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('user_auth:show_user'))
    
    
def show_user(request):
    """ This function displays a welcome page upos succesfull user login.
    
        """
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password
    })


def registration_page(request):
    """ This function registers new users by requesting the necessarry information.
        
        """
    form = CreateUserForm()
    
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    
    context = {'form':form}
    return render(request,"authentication/register.html",context)

hyperion/user_auth/templates/authentication/header.html
<!DOCTYPE html>

<p> user being registered</p>

hyperion/user_auth/templates/authentication/login.html
<!DOCTYPE html>
<html>
<head> 


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

	<link href = "/static/register.css" rel = "stylesheet" type = "text/css">

</head>

<div class = 'row'>
<h1> Login as User </h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>
</div>

</html>

hyperion/user_auth/templates/authentication/register.html
<!DOCTYPE html>
<html>
<head> 


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

	<link href = "/static/register.css" rel = "stylesheet" type = "text/css">

</head>


<div class = 'row'>
	<div class = 'col-md-3 text-truncate'>
		<h1> Register User</h1>
	</div>
</div>
		

<div class = 'row'>
	<div class = 'col-md-3 text-truncate'>
<form method = 'POST' action = ''>
	{% csrf_token %}
	{{form.first_name.label}}
	{{form.first_name}}
	<br>

	{{form.last_name.label}}
	{{form.last_name}}
	<br>

	{{form.username.label}}
	{{form.username}}
	<br>

	{{form.email.label}}
	{{form.email}}
	<br>

	{{form.password1.label}}
	{{form.password1}}
	<br>

	{{form.password2.label}}
	{{form.password2}}
	<br>

	<input type ='submit' name = 'Create User'>

</form>

<p> Already Registered as a User?</p>
<br>
<a href = '//127.0.0.1:8000/user_auth/login/'> Login</a>

</div>
</div>
</html>

hyperion/user_auth/templates/authentication/user.html
{% load static%}
<!DOCTYPE html>
<html>
<head> 


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

	<link href = "/static/register.css" rel = "stylesheet" type = "text/css">

</head>
<div class = 'row'>
<h1> Welcome, {{username}} </h1>
<p> Your password is {{password}}</p>

<nav>

	<span>Hello,{{request.user}}</span>
	<br>
	<span><a href = '{%url 'logout'%}'>Logout</a></span>

</nav>



<a href = '//127.0.0.1:8000/polls' target="_blank" > Vote on some polls</a>
<br>

<a href = '//127.0.0.1:8000/blog' target="_blank"> See Sam's Blog Posts</a>
<br>

<a href = '//127.0.0.1:8000/webapp' target="_blank"> See Sam's CV</a>
<br>

{% if request.user.is_superuser%}
	<p> Hello SuperUser</p>
	<a href '//127.0.0.1:8000/user_auth/register' target="_blank"> Register a New User</a>

{% endif %}

</div>