hyperion/blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 16 11:28:56 2023

@author: sam
"""

from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post
urlpatterns = [
    path('',
        ListView.as_view(
            queryset=
            Post.objects.all().order_by("-date")[:25],
            template_name="blog.html"
            )
        ),
    path('<int:pk>/',
        DetailView.as_view(
            model = Post,
            template_name="post.html"
) ),
]

hyperion/hyperion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/',include("webapp.urls")),
    path('blog/',include("blog.urls")),
    path('polls/',include("polls.urls")),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('', include("user_auth.urls"))
    
]

hyperion/polls/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 17 14:43:41 2023

@author: sam
"""

from django.urls import path, include, re_path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
	
  
]

import user_auth 
from user_auth import views

urlpatterns.append( path('user_auth',views.authenticate_user, name='login'))

hyperion/polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    """ This class defines the question object, which the superuser can create
        from the admin page. 

        :param str question_text: This simply stores the actual question. 
        :param date pub_date: This stores the date that the question was published 
            on the site. """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self): 
        """ This method returns the question and displays it to the user"""
        return self.question_text
    
class Choice(models.Model):
    """ This class defines the choice object which will correspond to each question
        
        :param str question: This uses the models module to correspond the question 
            to its possible choice
        :param str choice_text: This stores the text of the different choices.
        :param int votes: This variable stores the number of votes on each choice, and 
            defaults to 0 when creating a new choice. """
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self): 
        """This method displays the choices to the user"""
        return self.choice_text

    
    

hyperion/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate,login
from django.apps import apps


from user_auth import views 

# Create your views here.





@login_required(login_url = '//127.0.0.1:8000/user_auth/login/')
def index(request):
    """This function will display the different polls to the user, after they have logged in.
    
    :param latest_question_list: This orders, in a list, the polls by the date that they were published
    :type latest_question_list: list
    :param context: This creates a dictionary, with the corresponding text and poll.
    :type context: dictionary
    
    """ 
        
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/poll.html", context)
   
@login_required(login_url= '//127.0.0.1:8000/user_auth/login/')  
def detail(request, question_id):
    """This function will display a specific poll to the user, after they have logged in.
    
        :param question: This is a variable storing the question which the user selected. 
        :type question: str
        """ 
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
    
@login_required(login_url='//127.0.0.1:8000/user_auth/login/')  
def results(request, question_id):
        """This function will display the selected poll to the user and the results after they have
        voted on the poll, after they have logged in.
    
        :param question: This is a variable storing the question which the user selected. 
        :type question: str
        
        """ 
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', {'question': question})
    
@login_required(login_url='//127.0.0.1:8000/user_auth/login/')   
def vote(request, question_id):
        """This function will allow the user to vote on a specific poll, after they have logged in.
            This function also stores the result of the user's vote to display later.
    
            :param question: This is a variable storing the question which the user selected. 
            :type question: str
            :param selected_choice: This variable stores the users choice on the vote. 
                If the user did not select a choice then an error message will appear, and 
                they will be prompted to vote again.
            :param int selected_choice.votes: This is a tally variable. It stores the number of votes
                that are on each choice of a poll question. After a tally has been added to this variable
                the state is stored. 

            """ 
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(
                pk=request.POST['choice']
            )
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice."
    }) 
        else:
            selected_choice.votes += 1
            selected_choice.save()
          # Always return an HttpResponseRedirect after successfully
          # dealing with POST data. This prevents data from being
          # posted twice if a
          # user hits the Back button.
            return HttpResponseRedirect(
                reverse('polls:results', args=(question_id,))
                )

        

hyperion/polls/templates/polls/detail.html
<!DOCTYPE html>
{% load static %}
<html> 
  <head>

	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <link href = "/static/polls_ssheet.css" rel = "stylesheet" type = "text/css">


   
  </head>

<div class ='row'>
	<div class = 'col-md-4'> 
	</div>
	<div class = 'col-md-3'>
<h1> {{question.question_text}}</h1>
{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice {{
        forloop.counter
    }}" value="{{ choice.id }}" />
    <label for="choice {{ forloop.counter }}">
        {{ choice.choice_text }}
    </label>
    <br />
    {% endfor %}
    <button type="submit" class = "btn btn-primary">Vote</button>
</form>
</div>

</html>

hyperion/polls/templates/polls/poll.html
<!DOCTYPE html>
{% load static %}
<html> 
  <head>

	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <link href = "/static/polls_ssheet.css" rel = "stylesheet" type = "text/css">


   
  </head>


<div class ='row'>
	<div class = 'col-md-4'> 
	</div>
	
	<div class = 'col-md-3' id = 'all_polls'>
	<h1> Here are the active polls</h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href = "{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
</a> </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
</div>
</html>

hyperion/polls/templates/polls/results.html
<!DOCTYPE html>
{% load static %}
<html> 
  <head>

	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <link href = "/static/polls_ssheet.css" rel = "stylesheet" type = "text/css">


   
  </head>

<div class ='row'>
	<div class = 'col-md-4'> 
	</div>
	<div class = 'col-md-3'>
<h1> {{ question.question_text }} </h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes}}
        vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">
    Vote again?
</a> 
</div>